development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:pb28e730d6bdcb46966c40f736eec0135ce5d43fe5caa60808265076fc5268e98@ec2-54-87-193-47.compute-1.amazonaws.com:28749
  # url: redis://localhost:6379/1

